server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_db?serverTimezone=UTC&useSSL=false
    username: root
    password: bny031200@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # 개발 중에는 update, 운영 시에는 validate 또는 none 사용
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: Y7wHuhg2X2qDGXRp77OeKpHeM1N2RmI59v7eYTsTvvsmk4dIFxK0O9cmbCC2Ou4A
  expiration: 86400000 # 24시간 (밀리초 단위)